server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce-user
    username: postgres
    password: 1997
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      access-secret-key:  404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      refresh-secret-key: 304E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 2592000000 # 5 min (300000)
      refresh-token:
        expiration: 2592000000 # 30 days
