spring:
  application:
    name: API-Gateway

  cloud:
    gateway:
      routes:
        - id: transaction.service
          uri: lb://transaction.service
          predicates:
            - Path=/v1/transactions/**
        - id: notification.service
          uri: lb://notification.service
          predicates:
            - Path=/v1/notification/**
        - id: product.service
          uri: lb://product.service
          predicates:
            - Path=/v1/product/**
        - id: user.service
          uri: lb://user.service
          predicates:
            - Path=/api/v1/auth/**

server:
  port: 9093
eureka:
  instance:
    hostname: localhost